import type { Metadata } from "next";
import { Mooli } from "next/font/google";
import "./globals.css";

import { TanstackProviders } from "./TanstackProviders";
import "/css/fontStyle.css";
import "/css/Uiverse.css";
import NavBarButton from "./components/NavBarButton";

const fontStyle = Mooli({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Next Practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning={true}>
      <body className={fontStyle.className}>
        <TanstackProviders>
          <NavBarButton />
          {children}
        </TanstackProviders>
      </body>
    </html>
  );
}
